site_name: toy-data-web-app
repo_url: https://github.com/dataxight/toy-data-web-app
site_url: https://dataxight.github.io/toy-data-web-app
site_description: This is a toy example of a data web application built using a modern data tech stack
site_author: michael pan
edit_uri: edit/main/docs/
repo_name: dataxight/toy-data-web-app
copyright: Maintained by <a href="https://dataxight.com">DataXight</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dataxight/toy-data-web-app
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/toy-data-web-app

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
